Практика_задание2/Практика_задание2/Controllers/News_DraftController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Практика_задание2.Controllers
{
    [Authorize]
    public class News_DraftController : BaseController
    {
        private News_PortalEntities db = new News_PortalEntities();
        // GET: News_Draft
        public ActionResult Index()
        {
            return View(db.News_draft.ToList());
        }

        
        [HttpGet]
        [Authorize(Roles="admin")]
        public ActionResult Create_News()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create_News(News_draft news_draft)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.News_draft.Add(news_draft);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ErrorMessage = ex.Message;
                return RedirectToAction("Error", "Base");
            }

            return View();

        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Delete_News(int id)
        {
            try
            {
                News_draft nd = db.News_draft.Find(id);
                if (nd == null)
                {
                    return HttpNotFound();
                }
                return View(nd);
            }
            catch (Exception ex)
            {
                ErrorMessage = ex.Message;
                return RedirectToAction("Error", "Base");
            }

        }

        [HttpPost, ActionName("Delete_News")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                News_draft nd = db.News_draft.Find(id);
                if (nd == null)
                {
                    return HttpNotFound();
                }
                db.News_draft.Remove(nd);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ErrorMessage = ex.Message;
                return RedirectToAction("Error", "Base");
            }

        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Edit_News(int? id)
        {
           
            if (id == null)
            {
                return HttpNotFound();
            }
            News_draft nd = db.News_draft.Find(id);
            if (nd != null)
            {
                return View(nd);
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult Edit_News(News_draft nd)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(nd).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (Exception ex)
            {
                ErrorMessage = ex.Message;
                return RedirectToAction("Error", "Base");
            }

        }


        [Authorize]
        public ActionResult Publish_News(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            News_draft nd = db.News_draft.Find(id);
            if (nd != null)
            {
                return View(nd);
            }
            return HttpNotFound();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Publish_News(int id)
        {
            try
            {
                var news = db.News_draft.Where(m => m.ID == id).FirstOrDefault();
                news.publish = true;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ErrorMessage = ex.Message;
                return RedirectToAction("Error", "Base");
            }
        }


    }
}

Практика_задание2/Практика_задание2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Новостной портал", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                    <li>@Html.ActionLink("Публикация статей", "Index", "News_Draft")</li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>  @Html.ActionLink("Выйти", "Logoff", "Account")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Войти", "Login", "Account")</li>
                        @Html.Label(" | ");
                        <li>@Html.ActionLink("Регистрация", "Register", "Account")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>